In [3]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

In [15]:
print(iris.data)
print(iris.data.shape)
print(iris.target_names)
print(iris.target)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [16]:
print(digits.data)
print(digits.data.shape)
print(digits.target_names)
print(digits.target)

[[  0.   0.   5. ...,   0.   0.   0.]
 [  0.   0.   0. ...,  10.   0.   0.]
 [  0.   0.   0. ...,  16.   9.   0.]
 ..., 
 [  0.   0.   1. ...,   6.   0.   0.]
 [  0.   0.   2. ...,  12.   0.   0.]
 [  0.   0.  10. ...,  12.   1.   0.]]
(1797, 64)
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 ..., 8 9 8]


In [44]:
n = 100
train_X = digits.data[:-n ,:]
train_y = digits.target[:-n]

test_X = digits.data[-n:,:]
y_true = digits.target[-n:]

In [45]:
from sklearn import svm

In [46]:
svm_model = svm.SVC(gamma=0.001, C=100.)
# train svm model
svm_model.fit(train_X, train_y)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [47]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression()
# train lr model
lr_model.fit(train_X,train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [48]:
y_pred_svm = svm_model.predict(test_X)
y_pred_lr = lr_model.predict(test_X)

In [52]:
from sklearn.metrics import accuracy_score

print('SVM result：',accuracy_score(y_true,y_pred_svm))
print('LR result：',accuracy_score(y_true,y_pred_lr))

SVM result： 0.98
LR result： 0.94


In [51]:
# save model
# import pickle
# with open('svm_model.pkl','wb') as f:
#     pickle.dump(svm_model, f)

In [55]:
# import numpy as np
# # load model
# with open('svm_model.pkl','rb') as f:
#     model = pickle.load(f)

SyntaxError: invalid syntax (<ipython-input-55-9f415c103ee0>, line 6)